"""
配置模块
"""
from .business_rules import (
    SUBSIDY_RULES,
    DEFAULT_SUBSIDY_RULE,
    SUBSIDY_VALID_UNTIL,
    MONTHLY_SUBSIDY_LIMIT,
    MERCHANT_CATEGORIES,
    DECORATION_STYLES,
    DECORATION_PROCESS,
    MERCHANT_ONBOARDING,
    CUSTOMER_SCRIPTS,
    BEST_CONTACT_TIMES,
)

__all__ = [
    "SUBSIDY_RULES",
    "DEFAULT_SUBSIDY_RULE",
    "SUBSIDY_VALID_UNTIL",
    "MONTHLY_SUBSIDY_LIMIT",
    "MERCHANT_CATEGORIES",
    "DECORATION_STYLES",
    "DECORATION_PROCESS",
    "MERCHANT_ONBOARDING",
    "CUSTOMER_SCRIPTS",
    "BEST_CONTACT_TIMES",
]
