"""
提示词模块
"""
from .c_end_prompts import (
    C_END_SYSTEM_PROMPT,
    C_END_USER_CONTEXT_PROMPT,
    C_END_SUBSIDY_PROMPT,
    C_END_MERCHANT_RECOMMEND_PROMPT,
)
from .b_end_prompts import (
    B_END_SYSTEM_PROMPT,
    B_END_MERCHANT_CONTEXT_PROMPT,
    B_END_ONBOARDING_PROMPT,
    B_END_DATA_PRODUCT_PROMPT,
    B_END_CUSTOMER_ACQUISITION_PROMPT,
)

__all__ = [
    "C_END_SYSTEM_PROMPT",
    "C_END_USER_CONTEXT_PROMPT",
    "C_END_SUBSIDY_PROMPT",
    "C_END_MERCHANT_RECOMMEND_PROMPT",
    "B_END_SYSTEM_PROMPT",
    "B_END_MERCHANT_CONTEXT_PROMPT",
    "B_END_ONBOARDING_PROMPT",
    "B_END_DATA_PRODUCT_PROMPT",
    "B_END_CUSTOMER_ACQUISITION_PROMPT",
]
